"""
agents/schema_discovery_agent.py — Orchestrates table profiling and manages the profile cache.

Responsibilities:
  1. Parse the table reference into its three components.
  2. Check whether a fresh cached DatasetProfile exists on disk.
  3. Cache hit  → load, validate, and return it. No BigQuery queries run.
  4. Cache miss → run the profiling pipeline, assemble a DatasetProfile,
                  write it to cache, and return it.

This is the only place in the platform that constructs DatasetProfile objects
and reads/writes the JSON cache.
"""

import json
import logging
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from pathlib import Path
from typing import Any

from config.settings import settings
from core.bigquery_client import BigQueryClient
from core.dataset_profiler import DatasetProfiler
from models.dataset import DatasetProfile

logger = logging.getLogger(__name__)


# ── JSON serialisation ─────────────────────────────────────────────────────────

class _ProfileEncoder(json.JSONEncoder):
    """
    Handles types that BigQuery returns inside sample_rows and sample_values
    that the stdlib json module cannot serialise by default.
    """

    def default(self, obj: Any) -> Any:
        if isinstance(obj, Decimal):
            # Precision loss is acceptable — these are display values only.
            return float(obj)
        if isinstance(obj, datetime):
            return obj.isoformat()
        return super().default(obj)


# ── Table ref parsing ──────────────────────────────────────────────────────────

def _parse_table_ref(table_ref: str) -> tuple[str, str, str]:
    """
    Split a BigQuery table reference into (project, dataset_id, table_id).

    Accepts:
      "project.dataset.table"  →  ("project", "dataset", "table")
      "dataset.table"          →  (settings.gcp_project, "dataset", "table")

    Raises:
      ValueError: if the ref cannot be split into 2 or 3 dot-separated parts.
    """
    parts = table_ref.strip().split(".")
    if len(parts) == 3:
        return parts[0], parts[1], parts[2]
    if len(parts) == 2:
        return settings.gcp_project, parts[0], parts[1]
    raise ValueError(
        f"Invalid table reference '{table_ref}'. "
        "Expected 'project.dataset.table' or 'dataset.table'."
    )


# ── SchemaDiscoveryAgent ───────────────────────────────────────────────────────

class SchemaDiscoveryAgent:
    """
    Entry point for understanding a BigQuery table.

    Returns a fully populated DatasetProfile — either from the JSON cache or
    freshly generated by running the profiling pipeline.

    Cache behaviour is controlled entirely by settings:
      - cache_dir           where JSON files are stored
      - cache_max_age_hours how long a cached profile is considered fresh
                            (set to 0 to always re-profile)
    """

    def __init__(self, bq: BigQueryClient) -> None:
        """
        Args:
            bq: An initialised BigQueryClient. Injected so tests can substitute
                a mock without touching GCP or the filesystem.
        """
        self._bq = bq
        self._profiler = DatasetProfiler(bq)

    # ── Public API ─────────────────────────────────────────────────────────────

    def run(self, table_ref: str) -> DatasetProfile:
        """
        Return a DatasetProfile for the given table, using cache when available.

        Args:
            table_ref: Fully-qualified BigQuery table reference —
                       "project.dataset.table" or "dataset.table".

        Returns:
            A fully populated DatasetProfile.
        """
        project, dataset_id, table_id = _parse_table_ref(table_ref)
        cache_path = self._cache_path(project, dataset_id, table_id)

        # ── Cache read ─────────────────────────────────────────────────────────
        if settings.cache_max_age_hours > 0:
            cached = self._load_cache(cache_path)
            if cached is not None:
                logger.info(
                    "Cache hit: %s (profiled at %s)",
                    table_ref,
                    cached.profiled_at.isoformat(),
                )
                return cached

        # ── Profile ────────────────────────────────────────────────────────────
        logger.info("Cache miss — profiling %s", table_ref)

        # Fetch table-level metadata for row_count, size_bytes, and description.
        # DatasetProfiler also calls get_table internally for the schema —
        # two free metadata calls is acceptable to keep the profiler's API clean.
        table = self._bq.get_table(table_ref)
        table_location = table.location or ""
        columns, sample_rows = self._profiler.profile(table_ref, location=table_location)

        profile = DatasetProfile(
            table_ref=table_ref,
            project=project,
            dataset_id=dataset_id,
            table_id=table_id,
            row_count=table.num_rows or 0,
            size_bytes=table.num_bytes or 0,
            table_description=table.description or None,
            location=table_location,
            columns=columns,
            sample_rows=sample_rows,
        )

        # ── Cache write ────────────────────────────────────────────────────────
        self._write_cache(cache_path, profile)

        return profile

    # ── Private: cache helpers ─────────────────────────────────────────────────

    def _cache_path(self, project: str, dataset_id: str, table_id: str) -> Path:
        """Build the cache file path for the given table components."""
        return settings.cache_dir / f"{project}__{dataset_id}__{table_id}.json"

    def _load_cache(self, path: Path) -> DatasetProfile | None:
        """
        Load a cached DatasetProfile from disk and check its freshness.

        Returns None when:
          - the file does not exist
          - the file cannot be parsed (corrupt or schema mismatch)
          - the profile is older than cache_max_age_hours

        Errors are swallowed intentionally — a bad cache file must trigger a
        fresh profile rather than crashing the platform.
        """
        if not path.exists():
            return None

        try:
            profile = DatasetProfile.model_validate_json(
                path.read_text(encoding="utf-8")
            )
        except Exception:
            logger.warning("Unreadable cache file %s — will re-profile", path)
            return None

        age = datetime.now(timezone.utc) - profile.profiled_at
        if age > timedelta(hours=settings.cache_max_age_hours):
            logger.info("Cache stale (age=%s) — will re-profile", age)
            return None

        return profile

    def _write_cache(self, path: Path, profile: DatasetProfile) -> None:
        """
        Serialise a DatasetProfile to JSON and write it to the cache directory.

        model_dump(mode="json") converts Pydantic-known types (datetime → str,
        enums → str). _ProfileEncoder handles Any-typed fields that may contain
        Decimal or datetime objects returned by BigQuery.
        """
        path.parent.mkdir(parents=True, exist_ok=True)
        payload = json.dumps(
            profile.model_dump(mode="json"),
            indent=2,
            cls=_ProfileEncoder,
        )
        path.write_text(payload, encoding="utf-8")
        logger.info("Profile cached to %s", path)
